version: "3"

services:

  postgres:
    image: postgres
    container_name: school-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: school
      POSTGRES_PASSWORD: school
    volumes:
      - ./docker/data/postgres:/var/lib/postgresql/data